development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: api-service_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: api-service_production
